export const articles = [
    {
      id: '1',
      title: 'Sample Article 1',
      content: 'Curabitur fringilla fabitur fringilla felis ut augue convallis vestibulum.tur fringilla felis ut augue convallis vesnvallis vestibulum.a furabitur fringilla felis ut augue convallis vestibulum.elis ut augue convallis vestibulum.ut augue convallis vestibulum. vitae nisi sodales, nec venenatis eros efficitur.',
      createdAt: '2024-06-10T12:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover.svg',
    },
    {
      id: '2',
      title: 'Sample Article 2',
      content: 'Praesent volutpat justo et aliquam facilisis. Maecenas vel justo ut lorem eleifend aliquam.',
      createdAt: '2024-06-09T11:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover2.svg',
    },
    {
      id: '3',
      title: 'Sample Article 3',
      content: 'Curabitur fringilla felis ut augue convallis vestibulum. Sed auctor lorem urabitur fringilla urabiurabitur fringilla felis ut augue convallis vestibulum.tur fringilla felis ut augue convallis vestibulum.felis  urabitur fringillurabitur fringilla felis ut augue convallis vestibulum.a furabitur fringilla felis ut augue convallis vestibulum.elis ut augue convallis vestibulum.ut augue convallis vestibulum. vitae nisi sodales, nec venenatis eros efficitur.',
      createdAt: '2024-06-08T10:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover3.svg',
    },
    {
      id: '4',
      title: 'Sample Article 4',
      content: 'Vestibulum viverra odio nec nisi scelerisque feugiat. Suspendisse potenti.',
      createdAt: '2024-06-07T09:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover4.svg',
    },
    {
      id: '5',
      title: 'Sample Article 5',
      content: 'Fusce euismod sapien id nisi vehicula, a commodo nunc dictum. Integer sagittis ante non risus consectetur, ut tempus purus bibendum.',
      createdAt: '2024-06-06T08:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover5.svg',
    },
    {
      id: '6',
      title: 'Sample Article 6',
      content: 'Mauris tincidunt urna ut ex porttitor, in feugiat mauris tempor. Cras lacinia metus a lacus venenatis, ac luctus nisl auctor.',
      createdAt: '2024-06-05T07:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover6.svg',
    },
    {
      id: '7',
      title: 'Sample Article 7',
      content: 'Nam eu urna quis libero varius dapibus. Ut posuere lectus et felis hendrerit, a fringilla lectus iaculis.',
      createdAt: '2024-06-04T06:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover7.svg',
    },
    {
      id: '8',
      title: 'Sample Article 8',
      content: 'Proin quis nisl sit amet lacus pharetra commodo. Donec viverra lacus a lacinia eleifend.',
      createdAt: '2024-06-03T05:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover8.svg',
    },
    {
      id: '9',
      title: 'Sample Article 9',
      content: 'Nullam auctor libero non libero dapibus, eu luctus orci fermentum. Vivamus in risus ac magna consequat auctor.',
      createdAt: '2024-06-02T04:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover9.svg',
    },
    {
      id: '10',
      title: 'Sample Article 10',
      content: 'Etiam at dui sit amet sapien dapibus condimentum. Integer luctus nulla a purus gravida vestibulum.',
      createdAt: '2024-06-01T03:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover10.svg',
    },
    {
      id: '11',
      title: 'Sample Article 11',
      content: 'Sed scelerisque nunc a nisi viverra, sed vestibulum ex tristique. Aliquam erat volutpat.',
      createdAt: '2024-05-31T02:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover11.svg',
    },
    {
      id: '12',
      title: 'Sample Article 12',
      content: 'Integer sit amet felis quis sapien auctor dictum. Sed ut erat ac turpis sodales euismod.',
      createdAt: '2024-05-30T01:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover12.svg',
    },
    {
      id: '13',
      title: 'Sample Article 13',
      content: 'Duis faucibus velit sit amet risus accumsan hendrerit. Nam in nisi non justo interdum venenatis.',
      createdAt: '2024-05-29T12:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover13.svg',
    },
    {
      id: '14',
      title: 'Sample Article 14',
      content: 'Cras ac metus sed ligula cursus gravida. Fusce dignissim arcu et urna blandit, ac sagittis risus cursus.',
      createdAt: '2024-05-28T11:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover14.svg',
    },
    {
      id: '15',
      title: 'Sample Article 15',
      content: 'Vivamus tristique odio et arcu varius fermentum. Morbi varius lectus eget nisi varius, ut laoreet mi suscipit.',
      createdAt: '2024-05-27T10:00:00Z',
      imageSrc: '/assets/gallery/Carnival/cover15.svg',
    },
  ];